"""Python back-end.

Because the IR came from Python, this back-end is essentially a pretty-printer:
it demonstrates the IR is faithful (source -> IR -> Python round-trip) and reuses
the exact same hole machinery as the other targets — the compiler never special-
cases the "easy" target.
"""
from __future__ import annotations

from .. import ir
from .base import Emitter, iter_holes


class PyGen:
    def __init__(self, module: ir.Module):
        self.module = module
        self.e = Emitter("    ")

    def generate(self) -> str:
        self.e.line("# generated by poly -> python")
        for hole in iter_holes(self.module):
            self._hole_def(hole)
        for fn in self.module.funcs:
            self._function(fn)
        for stmt in self.module.body:
            self._stmt(stmt)
        return self.e.code()

    # ---- holes ------------------------------------------------------------
    def _hole_def(self, hole: ir.Hole) -> None:
        c = hole.contract
        params = ", ".join(c.param_names)
        self.e.line(f"def {c.fn_name}({params}):")
        self.e.indent()
        body = hole.filled.get("py")
        if body:
            for ln in body.strip().splitlines():
                self.e.line(ln)
        else:
            self.e.line(f'raise NotImplementedError("UNSUPPORTED: {c.kind}")')
        self.e.dedent()
        self.e.line()

    # ---- functions --------------------------------------------------------
    def _function(self, fn: ir.Function) -> None:
        params = []
        for p in fn.params:
            params.append(p.name if p.default is None else f"{p.name}={self._expr(p.default)}")
        self.e.line(f"def {fn.name}({', '.join(params)}):")
        self.e.indent()
        for s in fn.body:
            self._stmt(s)
        self.e.dedent()
        self.e.line()

    # ---- statements -------------------------------------------------------
    def _stmt(self, node) -> None:
        k = type(node).__name__
        if k == "Assign":
            self.e.line(f"{self._expr(node.target)} = {self._expr(node.value)}")
        elif k == "ExprStmt":
            self.e.line(self._expr(node.value))
        elif k == "If":
            self._if(node, "if")
        elif k == "While":
            self.e.line(f"while {self._expr(node.test)}:")
            self._block(node.body)
        elif k == "For":
            self.e.line(f"for {node.var} in {self._iterable(node.iterable)}:")
            self._block(node.body)
        elif k == "Return":
            self.e.line("return" if node.value is None else f"return {self._expr(node.value)}")
        elif k == "Pass":
            self.e.line("pass")
        elif k == "Break":
            self.e.line("break")
        elif k == "Continue":
            self.e.line("continue")
        else:
            raise RuntimeError(f"py backend: cannot emit {k}")

    def _if(self, node, kw: str) -> None:
        self.e.line(f"{kw} {self._expr(node.test)}:")
        self._block(node.body)
        if not node.orelse:
            return
        if len(node.orelse) == 1 and type(node.orelse[0]).__name__ == "If":
            self._if(node.orelse[0], "elif")
        else:
            self.e.line("else:")
            self._block(node.orelse)

    def _block(self, stmts: list) -> None:
        self.e.indent()
        if not stmts:
            self.e.line("pass")
        for s in stmts:
            self._stmt(s)
        self.e.dedent()

    def _iterable(self, node) -> str:
        if isinstance(node, ir.Range):
            return f"range({self._expr(node.start)}, {self._expr(node.stop)}, {self._expr(node.step)})"
        return self._expr(node)

    # ---- expressions ------------------------------------------------------
    def _expr(self, node) -> str:
        k = type(node).__name__
        if k == "Const":
            return repr(node.value)
        if k == "Name":
            return node.id
        if k == "ListLit":
            return "[" + ", ".join(self._expr(e) for e in node.elems) + "]"
        if k == "BinOp":
            return f"({self._expr(node.left)} {node.op} {self._expr(node.right)})"
        if k == "UnaryOp":
            if node.op == "not":
                return f"(not {self._expr(node.operand)})"
            return f"({node.op}{self._expr(node.operand)})"
        if k == "BoolOp":
            return "(" + f" {node.op} ".join(self._expr(v) for v in node.values) + ")"
        if k == "Compare":
            return f"({self._expr(node.left)} {node.op} {self._expr(node.right)})"
        if k == "Call":
            return f"{node.func}(" + ", ".join(self._expr(a) for a in node.args) + ")"
        if k == "MethodCall":
            return f"{self._expr(node.obj)}.{node.method}(" + ", ".join(self._expr(a) for a in node.args) + ")"
        if k == "Index":
            return f"{self._expr(node.obj)}[{self._expr(node.index)}]"
        if k == "Range":
            return f"range({self._expr(node.start)}, {self._expr(node.stop)}, {self._expr(node.step)})"
        if k == "Hole":
            return f"{node.contract.fn_name}(" + ", ".join(node.contract.param_names) + ")"
        raise RuntimeError(f"py backend: cannot emit expression {k}")
